name: version

on:
  schedule:
    - cron:  '0 1 * * *'


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a check script
      run: bash scripts/check.sh
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.TOKEN }}
